server :
  port : 8090

app :
  version : "1.0.0"

spring :
  datasource :
    url : ${DB_URL}
    username : ${DB_USER}
    password : ${DB_PASSWORD}
  jpa :
    database-platform : org.hibernate.dialect.PostgreSQLDialect
    hibernate :
      ddl-auto : none
      show-sql : true
  kafka:
    bootstrap-servers: alexandre-Inspiron-7590:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

keycloak:
  realm: MyDemo
  auth-server-url : http://127.0.0.1:8080/auth
  ssl-required : external
  resource : api
  public-client: false
  credentials:
    secret : 1a0b2b6e-caf5-4640-be59-06938459b5df
  bearer-only: true
  security-constraints[0]:
    security-collections[0]:
      patterns[0]: /covidalert/api/*
    securityCollections[0]:
      methods[0]: GET
      methods[1]: PUT
      methods[2]: DELETE
      methods[3]: PATCH